Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: C:/Users/DELL/Desktop/Sem1/Sem1/Programming language/Python/Assignment1.py
Line 1: Alder
Abbreviations: ADE, ALR, ALE, ADR, ALD, AER

Line 2: Crab Apple
Abbreviations: CAL, CRB, CRL, CAE, CAB, CBL, CRE, CRP, CBE, CRA, CPP, CPL, CLE, CAP, CBP, CAA, CPE, CBA

Line 3: Common Ash
Abbreviations: CMO, CON, COS, CMH, COH, CNH, CAS, CMM, CNS, COM, COA, CAH, CNA, CMS, CSH, COO, CMA, CMN

Line 4: Silver Birch
Abbreviations: SLE, SVE, SVR, SRI, SRC, SLR, SIH, SII, SBR, SEI, SRH, SLC, SLH, SIV, SVC, SIE, SIC, SLI, SEB, SVH, SBC, SBH, SIB, SVI, SBI, SRR, SVB, SIR, SIL, SEH, SLB, SEC, SCH, SER, SLV, SRB

Line 5: Downy Birch
Abbreviations: DRH, DOC, DWR, DWC, DIC, DNY, DIH, DNI, DWB, DNH, DOW, DOH, DON, DWY, DYC, DOB, DNC, DNB, DBR, DNR, DBC, DYI, DYR, DIR, DRC, DCH, DBH, DWN, DBI, DOI, DOY, DWH, DYB, DWI, DOR, DYH

Line 6: European Beech
Abbreviations: ERA, EBH, EEN, EAH, EEE, ENH, EUP, ERO, EOE, EPH, EOP, EEB, EOH, ERE, EPE, EEC, ERP, EEH, EOB, EAN, EUR, EPB, EUN, EON, EAB, ERB, ECH, EBE, EUE, EAE, ENC, EPC, EAC, EUO, EUB, EBC, ERN, ENB, ERC, EUA, EPA, EEA, ENE, ERH, EOA, EPN, EUH, EOC, EUC

Line 7: Box
Abbreviations: BOX

Line 8: Wild Cherry
Abbreviations: WDY, WIL, WIE, WLE, WLH, WLD, WIH, WLR, WRR, WDC, WDE, WLY, WDR, WHE, WCR, WIR, WDH, WCY, WER, WRY, WCH, WIC, WLC, WID, WIY, WHR, WHY, WEY, WCE

Line 9: Bird Cherry
Abbreviations: BID, BDC, BRH, BIE, BEY, BIR, BIH, BHE, BHY, BDH, BCR, BDY, BHR, BIY, BDR, BER, BCH, BRD, BCY, BRR, BRE, BCE, BIC, BDE, BRY, BRC

Line 10: Blackthorn
Abbreviations: BTH, BAN, BON, BKT, BTO, BCN, BHN, BLK, BAK, BAO, BAR, BKO, BAT, BTN, BKH, BTR, BCK, BHO, BCR, BLH, BLN, BHR, BRN, BCT, BKN, BKR, BLA, BAH, BCH, BLO, BAC, BCO, BLC, BLR, BOR, BLT

Line 11: Wych Elm
Abbreviations: WYC, WYM, WHM, WLM, WHE, WEL, WYE, WCL, WYL, WCH, WHL, WEM, WCM, WCE, WYH

Line 12: Smooth-leaved Elm
Abbreviations: SML, SOV, SEM, SDE, SLE, SVE, SMO, STA, SDM, STM, SED, SME, SOT, STD, SHE, SOH, SOA, SEA, SVM, SOL, SAV, SDL, SVD, SHA, SAD, SMA, SHL, STE, SEL, SVL, STL, SOM, SHD, SOO, SHV, SEE, SAM, SMH, SOE, SAL, SMV, STH, SMM, SLD, SLM, SEV, SAE, SMT, SOD, SHM, STV, SLL, SMD, SLA, SLV

Line 13: Common Hawthorn
Abbreviations: CMT, CMO, CON, CAT, COA, CNT, CAR, CNW, CTO, CHH, CWR, CNH, CNN, CMM, COT, CTH, CTN, COM, CAW, CAH, CTR, CNR, CWO, CHT, COO, CHO, CMN, CRN, CWN, CMH, COH, CHR, CHN, CAN, COR, CHW, CAO, CWH, CMW, COW, CMR, CNO, CHA, CNA, CWT, CMA

Line 14: Midland Hawthorn
Abbreviations: MHW, MWN, MWR, MIT, MDN, MNR, MHN, MIH, MNO, MID, MAH, MIR, MNN, MDR, MTO, MNA, MOR, MDW, MLW, MNH, MWT, MLN, MAO, MHT, MWH, MTR, MAR, MLT, MWO, MDO, MDA, MLD, MLR, MAD, MAA, MTN, MDT, MTH, MHH, MAW, MHA, MDH, MDL, MLH, MIW, MLO, MAN, MIN, MON, MDD, MAT, MNW, MHR, MLA, MHO, MRN, MND, MIL, MIO, MIA, MNT

Line 15: Common Hazel
Abbreviations: CMO, CON, COA, CAZ, CZE, CNL, CHL, CNH, CMM, CML, COM, CAE, CEL, COO, CZL, CMN, CNZ, CAL, CMH, COH, CMZ, CHZ, CNE, COL, COZ, COE, CHE, CHA, CNA, CMA, CME

Line 16: European Hornbeam
Abbreviations: EHR, ERA, EPR, EEN, EPO, EEM, EEE, EAH, ENH, EHA, ENA, EHE, EUP, EUM, ERO, EOE, EBA, EAR, EPH, EOP, EER, EEB, EOH, EHM, ERE, EPE, EBM, EAN, ERP, EHB, EOB, ENO, ERM, EUR, EPB, EAO, EUN, EHN, EON, EAB, ERB, EAM, EUE, EOO, EAE, EBE, EUO, EHO, EUB, ENN, ERN, EOR, ENB, EEO, ENR, EUA, EPA, EAA, EEA, ENE, ERH, EPM, ERR, EOM, EOA, EPN, EUH, EEH, ENM

Line 17: European Holly
Abbreviations: ERL, ERA, EEN, EHY, EPO, EAH, ENH, ELL, EPY, EUP, ERO, EOE, EPH, EOP, EHL, EOH, ELY, EUY, EAL, ERE, EPE, EPL, EAN, ERP, ENO, EOL, EEY, EUR, EAO, EUN, EON, EOY, EUE, EOO, EUO, EHO, ERY, EUL, ERN, EEO, EUA, EPA, EEA, EEL, ENL, ERH, ENY, EOA, EPN, EUH, EEH, EAY

Line 18: Common Juniper
Abbreviations: CMO, CON, CJI, CNU, COP, CUE, CUR, CNI, CJR, CUI, CPE, CIE, CNN, CMM, COM, CPR, CJE, COO, CMN, CJP, CMU, COJ, CIR, CNP, CIP, COU, CMP, CJU, COR, CMJ, CNE, CER, CMI, CJN, CMR, COE, CUP, CNJ, COI, CUN, CNR, CME

Line 19: Small-leaved Lime
Abbreviations: SML, SEM, SDE, SLE, SVE, SDM, SED, SDI, SME, SIM, SEI, SEA, SVM, SAV, SDL, SVD, SAD, SAA, SIE, SMA, SEL, SVL, SLI, SAM, SEE, SAL, SMV, SLD, SAE, SMM, SLM, SEV, SAI, SVI, SMI, SLL, SMD, SLA, SLV

Line 20: Large-leaved Lime
Abbreviations: LRM, LAD, LRG, LLE, LGV, LIE, LDI, LGE, LRL, LEI, LAL, LAI, LAV, LGD, LGI, LLD, LVE, LVL, LLV, LGM, LAM, LRI, LRA, LLM, LVM, LGA, LGL, LDE, LEL, LAA, LLL, LEV, LEM, LRV, LLA, LRE, LEA, LEE, LAE, LED, LDM, LVI, LLI, LAG, LRD, LDL, LAR, LME, LIM, LVD

Line 21: Field Maple
Abbreviations: FEP, FLP, FEM, FMA, FEE, FML, FAL, FAP, FIA, FLD, FDP, FLA, FDM, FDE, FMP, FLL, FPE, FEL, FIM, FIP, FDL, FID, FPL, FEA, FED, FIE, FLM, FME, FIL, FAE, FLE, FDA

Line 22: Pedunculate Oak
Abbreviations: PNL, PDL, PEU, PDE, PNK, POA, PEA, PUE, PAK, PAT, PCL, PTE, PLE, PUK, PUT, PEE, PCA, PUA, PCU, PAO, PAA, PED, PCT, PUU, PEL, PEO, PNU, PCE, PLA, PDA, PAE, PTK, PDK, PTA, PLK, PEK, PDU, POK, PNO, PCO, PNE, PTO, PCK, PUO, PDT, PNA, PLT, PDO, PUN, PEC, PUC, PDN, PLO, PNT, PET, PNC, PDC, PUL, PEN

Line 23: Sessile Oak
Abbreviations: SES, SLE, SSO, SSA, SAK, SLK, SLO, SOA, SEI, SEA, SOK, SIE, SEL, SIA, SIO, SSL, SSE, SEO, SSI, SEE, SEK, SIK, SIL, SSS, SLA, SSK

Line 24: Scots Pine
Abbreviations: SCP, SON, STN, SCO, SOT, STP, SNE, SOI, SSP, SSN, STI, SIN, SIE, SCE, STE, SSE, SCS, SSI, SOE, SCN, SPI, SCI, SPE, SOP, SOS, STS, SCT, SPN

Line 25: Aspen
Abbreviations: ASN, ASE, APE, APN, ASP, AEN

Line 26: Black Poplar
Abbreviations: BPR, BOP, BCP, BKL, BLL, BLK, BAK, BCL, BAO, BAR, BKO, BKA, BPL, BPP, BCK, BCR, BAP, BLP, BAA, BKR, BOA, BLA, BAL, BCA, BPO, BLO, BAC, BCO, BKP, BLC, BLR, BOL, BOR, BPA

Line 27: European Rowan
Abbreviations: ERA, EPR, EEN, EPO, ENA, EUP, ERO, EOE, EWA, EAR, EER, EOP, EPW, ENW, ERE, EPE, EAN, ERP, ENO, EUR, EAO, EUN, EON, EWN, EUE, EOO, EUO, EAW, ENN, EOR, ERN, EOW, EEO, ENR, EUA, EPA, EEW, EUW, ERW, EAA, EEA, ERR, EOA, EPN

Line 28: Common Whitebeam
Abbreviations: CMT, CMO, CON, CIM, CEA, COA, CNT, CNW, CNI, CHB, CEB, CTE, CIE, CNH, CMM, COT, CNM, COM, CIB, CBE, CHM, CWE, CTA, CAM, CHT, CWB, CEE, COO, CMN, CMH, COH, CWA, CIT, CNE, CNB, CHI, COB, CMI, CWH, CMW, CBM, COW, CWI, CIA, CTB, COE, CHE, CWM, CHA, COI, CNA, CMB, CWT, CTM, CEM, CMA, CME, CBA

Line 29: Service Tree
Abbreviations: SVE, SRI, SRC, SVR, SRT, SEI, SCR, SVC, SIE, SCE, STE, SIC, SIT, SEE, STR, SEV, SRV, SVI, SRE, SRR, SIR, SEC, SCT, SVT, SET, SER

Line 30: Wild Service Tree
Abbreviations: WEI, WIL, WRT, WIS, WRC, WST, WIE, WVE, WSE, WEV, WIV, WLE, WVT, WSC, WVR, WVC, WSI, WII, WLD, WLT, WTE, WET, WLR, WRR, WTR, WVI, WDC, WDE, WDR, WCR, WIR, WER, WRI, WRE, WLI, WIC, WLC, WIT, WEE, WLS, WID, WSV, WSR, WDV, WDT, WLV, WEC, WRV, WDS, WCT, WCE, WDI

Line 31: Strawberry Tree
Abbreviations: SAY, SBE, STA, SAR, SRT, SWY, SBR, SRW, SWR, SYE, SWB, SWE, STB, SYT, SAW, STW, STE, SRY, SEY, SEE, STR, SYR, SAE, STY, SBT, SRA, SRE, SBY, SRR, STT, SET, SER, SAT, SWT, SAB, SRB

Line 32: Bay Willow
Abbreviations: BYL, BIW, BLL, BLW, BYW, BAO, BWL, BYO, BAW, BIL, BWO, BAY, BWI, BAI, BAL, BLO, BWW, BYI, BOW, BIO

Line 33: Crack Willow
Abbreviations: CWW, CAI, CCK, CLW, CRC, CCL, CCO, CRW, CAK, CKL, CRI, CRL, CAW, CIO, CLL, CWO, CKO, CWL, CIW, CAL, CRK, CRO, CIL, CCW, CKI, CRA, CAO, CWI, COW, CCI, CKW, CAC, CLO

Line 34: White Willow
Abbreviations: WLW, WEI, WIL, WHT, WIE, WWW, WEO, WLO, WTL, WTO, WII, WLL, WOW, WWL, WHL, WTE, WTI, WHO, WIW, WHE, WHW, WWI, WTW, WIT, WIO, WEW, WEL, WWO, WHI

Line 35: Almond-leaved Willow
Abbreviations: AOE, AOW, ALE, ANA, ALA, ADV, ANW, AWL, AVL, ALM, ALI, AOL, AOA, AEV, AAI, AAV, AVO, AAO, AWI, AMD, AAE, ALN, AML, ADE, ANL, ADL, AEI, ALL, AOD, ADO, AED, ADA, AEO, AVD, AVI, AEW, ALO, AAW, AAL, AOO, AEE, AIL, ALD, AON, AMN, ADD, ANI, ADI, AWW, AIO, ALV, AND, AAD, AMV, AME, AMA, AWO, AEA, AMW, AMI, AOI, ANV, ADW, ANO, AVW, AVE, AIW, AOV, ANE, ALW, AMO, AEL

Line 36: European Yew
Abbreviations: ERA, EEN, EEE, EPY, EUP, ERO, EOE, EOP, EPW, ENW, EUY, ERE, EPE, EYE, EAN, ERP, EEY, EUR, EUN, EON, EOY, EUE, EAE, EUO, EAW, ERY, ERN, EOW, EYW, EUA, EPA, EEW, EUW, ERW, EEA, ENE, ENY, EOA, EPN, EAY

Line 37: Alder Buckthorn
Abbreviations: AUH, AEK, ARU, ALT, ARK, ABO, ALE, AOR, AKT, ADC, ABT, AKR, ADT, AEB, ABN, AUO, ABC, ABU, AEH, ART, ALN, ALU, ADE, ADH, AEU, ABR, ARO, ADO, AUT, ACH, ACT, AKH, ALB, ADK, AEN, AEO, ARN, ARB, ATN, ARH, AUK, ACK, ALO, ALK, ALR, AKO, ADR, ATH, ARC, ALH, ADB, AEC, ALD, AUR, AON, AHN, AET, ACR, ATO, ADU, ACN, AHR, AUN, ACO, ATR, ABK, ABH, ARR, ALC, AUC, AHO, AKN, ADN, AER

Line 38: Purging Buckthorn
Abbreviations: PNG, PGC, PBR, PUB, PRK, PRN, PHN, PUR, PON, PRB, PHO, PUI, PNU, PRR, PNO, PIC, PGO, PIU, PRO, PNT, PKO, PIO, PIB, PHR, PBN, PIT, PRI, PGU, PCN, PUH, PBH, PCT, PUU, PCR, PBU, PIK, PUG, PTR, PBO, PCH, PKN, PNR, PRT, PIH, PIR, PKR, PUK, PRH, PBT, PBK, PGT, PBC, PGH, PKH, PGN, PCO, PIG, PCK, PUO, PNN, PRG, PUN, PGG, PUC, PTH, PNC, PGK, PTN, PNK, PGR, PRU, PIN, PUT, PNH, PGB, PGI, PKT, PTO, POR, PNB, PRC

Line 39: Elder
Abbreviations: ELD, ELE, ELR, EDR, EDE, EER

Line 40: Common Dogwood
Abbreviations: COD, CON, CMO, CNW, CND, CGW, CMM, COM, CDD, CWO, COO, CMN, COG, CDO, CNG, CDW, CMG, CMW, COW, CGD, CNO, CWD, CDG, CMD, CGO

Line 41: Rock Whitebeam
Abbreviations: RWM, RCA, RCE, RIB, RKM, RCW, RWE, RKB, REE, RKI, RTM, RKA, ROH, ROW, RHT, RIM, ROM, RIA, RCI, RBA, RKE, RTB, ROI, RHB, RBM, RCH, REB, ROC, RKH, RWB, RAM, RIT, ROK, RWT, ROT, RKW, RCT, RCK, ROE, RHE, RHM, RWA, RBE, RWH, RTA, REM, RTE, ROB, RCM, ROA, RKT, RWI, RHA, REA, RCB, RHI, RIE

Line 42: Sea-buckthorn
Abbreviations: SCK, SAU, SHO, SBU, SBK, SBO, SAK, SKT, SON, SUT, SAC, SKH, SAR, STN, SCO, SBR, SEA, SUK, SCR, SUC, SUO, SKN, SUH, STO, SAO, SBN, SEB, SEO, SEN, SKR, STR, SCN, SEU, SKO, SOR, SHR, SRN, SEK, SBC, SBH, STH, SHN, SBT, SUR, SEH, SUN, SEC, SAH, SAN, SCT, SET, SCH, SER, SAT, SAB

Line 43: Spindle
Abbreviations: SNE, SND, SDE, SLE, SDL, SPD, SIL, SNL, SIE, SIN, SPI, SPN, SPL, SPE, SID

Line 44: Sallow
Abbreviations: SLW, SOW, SAL, SLL, SAW, SLO, SAO

Line 45: Grey Willow
Abbreviations: GWL, GWW, GRY, GYW, GRW, GRE, GOW, GWO, GWI, GIO, GYI, GRI, GIL, GYO, GEY, GIW, GEW, GRL, GLW, GRO, GLL, GEL, GYL, GLO, GEO, GEI

Line 46: Purple Willow
Abbreviations: PUW, PRP, PRW, PWO, PIO, PUE, PUR, PRL, PPI, PLE, PLW, PRI, PLL, PPO, PUI, PLI, PIL, PEL, PEO, PPW, PPL, PEW, PWL, PWW, PEI, PUO, PPE, PWI, PRE, PUP, POW, PRO, PLO, PIW, PUL

Line 47: Common Osier
Abbreviations: CMO, CON, COS, CSR, CNS, CNI, CSI, CIE, CMM, COM, CMS, COO, CMN, CIR, COR, CNE, CSE, CER, CMI, CMR, COE, CNO, COI, CNR, CME

Line 48: Eared Willow
Abbreviations: ERL, EEI, ELL, EAI, ERO, ERD, EED, EDI, EAR, EIO, EAL, EIL, EDL, ERE, EWW, EWI, EAO, EAD, EWL, EDW, EAE, EIW, EAW, EOW, ERI, EEO, EEW, ERW, ELW, EEL, EDO, ELO, EWO

Line 49: Guelder Rose
Abbreviations: GRE, GOS, GLE, GUR, GSE, GDR, GDO, GES, GRR, GLR, GER, GUE, GLD, GLS, GUD, GRO, GEE, GUO, GEL, GOE, GUL, GDS, GLO, GRS, GUS, GED, GDE, GEO

Line 50: Wayfaring tree
Abbreviations: WNE, WYT, WRT, WAA, WFI, WIE, WAF, WGT, WYI, WYN, WGR, WFT, WFN, WGE, WAY, WYR, WYG, WAR, WTE, WIG, WFG, WNR, WFR, WRR, WAE, WYF, WIN, WTR, WFA, WFE, WYA, WRN, WRI, WYE, WIR, WRE, WIT, WEE, WRG, WAT, WAN, WNG, WNT, WAG, WAI

Line 51: Common Privet
Abbreviations: CMT, CMO, CON, CIV, CET, COP, CRT, CNT, CRE, CNI, CPE, CIE, CMM, COT, CMV, COM, CPR, CRI, COV, CRV, CPV, CPT, COO, CVT, CMN, CIT, CNP, CVE, CMP, COR, CNE, CMI, CMR, COE, CPI, COI, CNR, CME, CNV

Line 52: Plot's Elm
Abbreviations: PEM, PSL, PTE, PSM, PLE, PLL, POM, POT, PTS, PLM, PEL, PSE, POS, POE, PTL, PLT, POL, PLO, PTM, PLS

