Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:/Users/DELL/Desktop/Sem1/Sem1/Programming language/Python/Assignment1.py
ALDER
CRAB APPLE
COMMON ASH
SILVER BIRCH
DOWNY BIRCH
EUROPEAN BEECH
BOX
WILD CHERRY
BIRD CHERRY
BLACKTHORN
WYCH ELM
SMOOTHLEAVED ELM
COMMON HAWTHORN
MIDLAND HAWTHORN
COMMON HAZEL
EUROPEAN HORNBEAM
EUROPEAN HOLLY
COMMON JUNIPER
SMALLLEAVED LIME
LARGELEAVED LIME
FIELD MAPLE
PEDUNCULATE OAK
SESSILE OAK
SCOTS PINE
ASPEN
BLACK POPLAR
EUROPEAN ROWAN
COMMON WHITEBEAM
SERVICE TREE
WILD SERVICE TREE
STRAWBERRY TREE
BAY WILLOW
CRACK WILLOW
WHITE WILLOW
ALMONDLEAVED WILLOW
EUROPEAN YEW
ALDER BUCKTHORN
PURGING BUCKTHORN
ELDER
COMMON DOGWOOD
ROCK WHITEBEAM
SEABUCKTHORN
SPINDLE
SALLOW
GREY WILLOW
PURPLE WILLOW
COMMON OSIER
EARED WILLOW
GUELDER ROSE
WAYFARING TREE
COMMON PRIVET
PLOTS ELM
